# Generated by Django 5.1 on 2024-08-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_name', models.CharField(max_length=255, verbose_name='TV Name')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('port', models.PositiveIntegerField(verbose_name='Port')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
    ]
