# Generated by Django 5.1 on 2024-08-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv7_reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server',
            new_name='Sensor',
        ),
    ]
